trigger:
- master

variables:
- name: buildConfiguration
  value: Release
  
stages:
- stage: Build
  jobs:
  - job: Build 
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*UnitTests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)"'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Website'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/ArmTemplates'
        ArtifactName: 'Templates'
        publishLocation: 'Container'       

- stage: Release_Infrastructure_to_Azure
  dependsOn: Build
  jobs:
  - job: Release_Infrastructure_to_Azure
    pool: 
     vmimage: 'windows-latest'
    steps:

    - download: current
      artifact: Templates
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on vmyaml-rg'
      inputs: 
        azureSubscription: 'VMyaml - Azure'
        resourceGroupName: 'vmyaml-rg'
        location: 'West Europe'
        csmFile: 'ArmTemplates/windows-vm-template.json'
        overrideParameters: '--parameters webAppName="${{ env.AZURE_WEBAPP_NAME }}" hostingPlanName="${{ env.HOSTINGPLANNAME }}" appInsightsLocation="${{ env.APPINSIGHTLOCATION }}" sku="${{ env.SKU }}'

- stage: Publish_Website_to_WebApp
  dependsOn: Release_Infrastructure_to_Azure
  jobs: 
  - deployment: VMDeployment
    displayName: "Publish Website to Azure App Service"
    environment:
      name: "Prod-WebApp"
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: Website

     